title: Your awesome title
email: terentich@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/static-site" # the subpath of your site, e.g. /blog
url: ""
twitter_username: jekyllrb
github_username:  Terentich

# Build settings
theme: minima
plugins:
  - jekyll-feed
